#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}
os: Visual Studio 2019
configuration: Release
branches:
  only:
  - main

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  ha_secure:
    secure: NhOAZWl58l2RlmsMW0vbXzKZPf9TOrjC8BndGIYAgFBFQNfkORg7tFe6mhOU1XxF

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
    - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0\bin
    - SET PATH=%JAVA_HOME%\bin;%PATH%
before_build:
    - dotnet restore Generator.sln
    - dotnet tool install --global dotnet-sonarscanner
    - dotnet sonarscanner begin /o:"amitpnk" /k:"Amitpnk_Hexagonal-Arch-ASP.NET-Core" /d:sonar.host.url="https://sonarcloud.io" /d:"sonar.login=%ha_secure%" 
build:
    - dotnet build Generator.sln
after_build:
    - dotnet sonarscanner end

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# test_script:
# - run-tests.cmd

#---------------------------------#
#    notification configuration   #
#---------------------------------#
notifications:
- provider: Email
  to:
  - amit.naik8103@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
